#!/bin/bash

ASM="fasm"
BIN="${PWD##*/}"
SRC="$BIN.s"

LDLIBS="-lc -lX11"

$ASM $SRC && \
ld $BIN.o -o $BIN -dynamic-linker /lib/ld-linux-x86-64.so.2 $LDLIBS && \
strip -R .gnu.version -R .eh_frame $BIN; sstrip $BIN 2>/dev/null
